Vagrant.configure("2") do |config|
  # FLARE VM
  config.vm.define "flarevm" do |flarevm|
    flarevm.vm.box = "flarevm"
    flarevm.vm.hostname = "flarevm"
    flarevm.vm.guest = :windows
    flarevm.ssh.username = "admin"
    flarevm.ssh.password = "password"
    # flarevm.ssh.insert_key = false
    
    flarevm.vm.network "public_network", adapter: 0, auto_config: false
    flarevm.vm.network "private_network", adapter: 1, auto_config: false

    flarevm.vm.synced_folder '.', '/vagrant', disabled: true

    flarevm.vm.provider "vmware_desktop" do |vp|
      vp.vmx["ethernet0.present"]        = "TRUE"
      vp.vmx["ethernet0.connectionType"] = "nat"
      vp.vmx["ethernet0.virtualDev"]     = "e1000"
      vp.vmx["ethernet0.connect"]        = "connected"
      vp.vmx["ethernet0.startConnected"] = "TRUE"
      vp.vmx["ethernet0.displayName"]    = "nat"

      vp.vmx["ethernet1.present"]        = "TRUE"
      vp.vmx["ethernet1.connectionType"] = "hostonly"
      vp.vmx["ethernet1.virtualDev"]     = "e1000"
      vp.vmx["ethernet1.connect"]        = "connected"
      vp.vmx["ethernet1.startConnected"] = "TRUE"
      vp.vmx["ethernet1.displayName"]    = "hostonly"
      
      vp.memory = "4096"
      vp.gui    = true
    end
  end
end
