Vagrant.configure("2") do |config|
  # cape-server
  config.vm.define "cape-server" do |cape_server|
    cape_server.vm.box = "figment/cape-server"
    cape_server.vm.hostname = "cape-server"
    cape_server.ssh.username = "ubuntu"
    cape_server.ssh.password = "password"
    cape_server.ssh.insert_key = false 

    cape_server.vm.provider "vmware_desktop" do |vmware|
      vmware.vmx["ethernet0.present"]        = "TRUE"
      vmware.vmx["ethernet0.connectionType"] = "nat"
      vmware.vmx["ethernet0.virtualDev"]     = "e1000"
      vmware.vmx["ethernet0.connect"]        = "connected"
      vmware.vmx["ethernet0.startConnected"] = "TRUE"
      vmware.vmx["ethernet0.displayName"]    = "nat"

      vmware.vmx["ethernet1.present"]        = "TRUE"
      vmware.vmx["ethernet1.connectionType"] = "hostonly"
      vmware.vmx["ethernet1.virtualDev"]     = "e1000"
      vmware.vmx["ethernet1.connect"]        = "connected"
      vmware.vmx["ethernet1.startConnected"] = "TRUE"
      vmware.vmx["ethernet1.displayName"]    = "hostonly"
      
      vmware.memory = "8192"
      vmware.gui    = true
      vmware.cpus   = 4
    end

    cape_server.vm.provider "virtualbox" do |virtualbox|
      virtualbox.customize ["modifyvm", :id, "--nic1", "nat"]
      virtualbox.customize ["modifyvm", :id, "--macaddress1", "080027000001"]
      virtualbox.customize ["modifyvm", :id, "--nic2", "hostonly"]
      virtualbox.customize ["modifyvm", :id, "--macaddress2", "080027000002"]
      virtualbox.customize ["modifyvm", :id, "--hostonlyadapter2", "vboxnet0"]

      virtualbox.customize ["modifyvm", :id, "--accelerate3d", "on"]
      virtualbox.customize ["modifyvm", :id, "--vram", "128"]
          
      virtualbox.memory = "8192"
      virtualbox.gui    = true
      virtualbox.cpus   = 4
    end

    cape_server.vm.provider "libvirt" do |libvirt, override|
      libvirt.mgmt_attach    = false
      libvirt.nested = true 
      libvirt.cpu_mode = "host-passthrough"
      libvirt.cpus = 4

      override.vm.synced_folder ".", "/vagrant", disabled: true
      
      override.vm.network "forwarded_port",
        guest: 22,
        host: 2223,
        auto_correct: true

      override.vm.network "private_network",
        type: "dhcp",
        libvirt__model_type: "e1000",
        libvirt__network_name: "default",
        mac: "52:54:00:00:00:03"

      override.vm.network "private_network",
        type: "dhcp",
        libvirt__model_type: "e1000",
        libvirt__network_name: "hostonly",
        mac: "52:54:00:00:00:04"

      libvirt.memory = 8192
    end
  
  end
end
