Vagrant.configure("2") do |config|
  # cape-guest-ubuntu
  config.vm.define "cape-guest-ubuntu" do |cape_guest-ubuntu|
    cape_guest-ubuntu.vm.box = "cape-guest-ubuntu"
    cape_guest-ubuntu.vm.hostname = "cape-guest-ubuntu"
    cape_guest-ubuntu.ssh.username = "ubuntu"
    cape_guest-ubuntu.ssh.password = "password"
    cape_guest-ubuntu.ssh.insert_key = false  # Disable key injection

    # cape-guest-ubuntu.vm.network "public_network", adapter: 0, auto_config: false
    # cape-guest-ubuntu.vm.network "private_network", adapter: 1, auto_config: false

    cape_guest-ubuntu.vm.provider "vmware_desktop" do |vmware|
      vmware.vmx["ethernet0.present"]        = "TRUE"
      vmware.vmx["ethernet0.connectionType"] = "nat"
      vmware.vmx["ethernet0.virtualDev"]     = "e1000"
      vmware.vmx["ethernet0.connect"]        = "connected"
      vmware.vmx["ethernet0.startConnected"] = "TRUE"
      vmware.vmx["ethernet0.displayName"]    = "nat"

      vmware.vmx["ethernet1.present"]        = "TRUE"
      vmware.vmx["ethernet1.connectionType"] = "hostonly"
      vmware.vmx["ethernet1.virtualDev"]     = "e1000"
      vmware.vmx["ethernet1.connect"]        = "connected"
      vmware.vmx["ethernet1.startConnected"] = "TRUE"
      vmware.vmx["ethernet1.displayName"]    = "hostonly"
      
      vmware.memory = "8192"
      vmware.gui    = true
    end

    cape_guest-ubuntu.vm.provider "virtualbox" do |virtualbox|
      virtualbox.customize ["modifyvm", :id, "--nic1", "nat"]
      virtualbox.customize ["modifyvm", :id, "--macaddress1", "080027000001"]
      virtualbox.customize ["modifyvm", :id, "--nic2", "hostonly"]
      virtualbox.customize ["modifyvm", :id, "--macaddress2", "080027000002"]
      virtualbox.customize ["modifyvm", :id, "--hostonlyadapter2", "vboxnet0"]

      virtualbox.customize ["modifyvm", :id, "--accelerate3d", "on"]
      virtualbox.customize ["modifyvm", :id, "--vram", "128"]
          
      virtualbox.memory = "8192"
      virtualbox.gui    = true
    end
  
  end
end
