Vagrant.configure("2") do |config|
  # REMnux
  config.vm.define "remnux" do |remnux|
    remnux.vm.box = "remnux"
    remnux.vm.hostname = "remnux"
    remnux.vm.communicator = "none"

    remnux.vm.provider "vmware_desktop" do |vp|
      vp.vmx["ethernet0.present"] = "TRUE"
      vp.vmx["ethernet0.virtualDev"] = "e1000"
      vp.vmx["ethernet0.connectionType"] = "hostonly"
      vp.vmx["ethernet0.startConnected"] = "TRUE"
      vp.vmx["ethernet0.addressType"] = "generated"
      vp.vmx["ethernet0.pciSlotNumber"] = "33"
      vp.memory = "2048"
      vp.gui    = true
    end
  
  end
end
