Vagrant.configure("2") do |config|
  # REMnux
  config.vm.define "remnux" do |remnux|
    remnux.vm.box = "remnux"
    remnux.vm.hostname = "remnux"
    remnux.ssh.username = "remnux"
    remnux.ssh.password = "malware"
    remnux.ssh.insert_key = false  # Disable key injection

    remnux.vm.network "public_network", adapter: 0
    remnux.vm.network "private_network", ip: "172.16.53.100", adapter: 1

    remnux.vm.provider "vmware_desktop" do |vp|
      vp.memory = "2048"
      vp.gui    = true
    end
  
  end
end
