Vagrant.configure("2") do |config|
  # FLARE VM
  config.vm.define "cape-guest-win11" do | cape_guest_win11 |
    cape_guest_win11.vm.box = "cape-guest-win11"
    cape_guest_win11.vm.hostname = "cape-guest-win11"
    cape_guest_win11.vm.guest = :windows
    cape_guest_win11.ssh.username = "admin"
    cape_guest_win11.ssh.password = "password"
    cape_guest_win11.ssh.insert_key = false
    cape_guest_win11.ssh.shell = "powershell.exe -NoLogo -NonInteractive -ExecutionPolicy Bypass"

    cape_guest_win11.vm.synced_folder '.', '/vagrant', disabled: true

    cape_guest_win11.vm.provider "vmware_desktop" do |vmware|
      vmware.vmx["ethernet0.present"]        = "TRUE"
      vmware.vmx["ethernet0.connectionType"] = "nat"
      vmware.vmx["ethernet0.virtualDev"]     = "e1000"
      vmware.vmx["ethernet0.connect"]        = "connected"
      vmware.vmx["ethernet0.startConnected"] = "TRUE"
      vmware.vmx["ethernet0.displayName"]    = "nat"
      vmware.vmx["ethernet0.addressType"]    = "static"
      vmware.vmx["ethernet0.address"]        = "00:0c:29:00:00:01"
      vmware.vmx["ethernet0.pciSlotNumber"]  = "33"

      vmware.vmx["ethernet1.present"]        = "TRUE"
      vmware.vmx["ethernet1.connectionType"] = "hostonly"
      vmware.vmx["ethernet1.virtualDev"]     = "e1000"
      vmware.vmx["ethernet1.connect"]        = "connected"
      vmware.vmx["ethernet1.startConnected"] = "TRUE"
      vmware.vmx["ethernet1.displayName"]    = "hostonly"
      vmware.vmx["ethernet1.addressType"]    = "static"
      vmware.vmx["ethernet1.address"]        = "00:0c:29:00:00:02"
      vmware.vmx["ethernet1.pciSlotNumber"]  = "36" # (Windows 11) change to 32 to avoid hostonly NIC issues
      
      vmware.memory = "4096"
      vmware.gui    = true
    end

    cape_guest_win11.vm.provider "virtualbox" do |virtualbox|
      virtualbox.customize ["modifyvm", :id, "--nic1", "nat"]
      virtualbox.customize ["modifyvm", :id, "--macaddress1", "080027000001"]
      virtualbox.customize ["modifyvm", :id, "--nic2", "hostonly"]
      virtualbox.customize ["modifyvm", :id, "--macaddress2", "080027000002"]
      virtualbox.customize ["modifyvm", :id, "--hostonlyadapter2", "vboxnet0"]

      virtualbox.customize ["modifyvm", :id, "--accelerate3d", "on"]
      virtualbox.customize ["modifyvm", :id, "--vram", "128"]
          
      virtualbox.memory = "4096"
      virtualbox.gui    = true
    end

    cape_guest_win11.vm.provider :libvirt do |libvirt|
      libvirt.default_prefix = ""
      libvirt.driver = "kvm"
      libvirt.uri = "qemu:///system"
      libvirt.machine_type = "q35"
      libvirt.cpu_mode = "host-passthrough"
      libvirt.disk_bus = "sata"
      libvirt.disk_controller_model = "virtio-scsi"
      libvirt.cpus = 4
      libvirt.memory = 8192
      libvirt.nic_model_type = "e1000"
      libvirt.management_network_address = "192.168.56.0/24"
      libvirt.management_network_mode = "nat"
      libvirt.management_network_model_type = "e1000"
      libvirt.management_network_mac = "52:54:00:07:66:ea"
    end
  end
end
