Vagrant.configure("2") do |config|
  # REMnux
  config.vm.define "remnux" do |remnux|
    remnux.vm.box = "remnux-qemu"
    remnux.vm.hostname = "remnux"
    remnux.ssh.username = "remnux"
    remnux.ssh.password = "malware"
    remnux.ssh.insert_key = false  # Disable key injection
    remnux.vm.synced_folder ".", "/vagrant", disabled: true

    # remnux.vm.network "public_network", adapter: 0, auto_config: false
    # remnux.vm.network "private_network", adapter: 1, auto_config: false

    remnux.vm.provider "vmware_desktop" do |vmware|
      vmware.vmx["ethernet0.present"]        = "TRUE"
      vmware.vmx["ethernet0.connectionType"] = "nat"
      vmware.vmx["ethernet0.virtualDev"]     = "e1000"
      vmware.vmx["ethernet0.connect"]        = "connected"
      vmware.vmx["ethernet0.startConnected"] = "TRUE"
      vmware.vmx["ethernet0.displayName"]    = "nat"

      vmware.vmx["ethernet1.present"]        = "TRUE"
      vmware.vmx["ethernet1.connectionType"] = "hostonly"
      vmware.vmx["ethernet1.virtualDev"]     = "e1000"
      vmware.vmx["ethernet1.connect"]        = "connected"
      vmware.vmx["ethernet1.startConnected"] = "TRUE"
      vmware.vmx["ethernet1.displayName"]    = "hostonly"
      
      vmware.memory = "2048"
      vmware.gui    = true
    end

    remnux.vm.provider "virtualbox" do |virtualbox|
      virtualbox.customize ["modifyvm", :id, "--nic1", "nat"]
      virtualbox.customize ["modifyvm", :id, "--macaddress1", "080027000001"]
      virtualbox.customize ["modifyvm", :id, "--nic2", "hostonly"]
      virtualbox.customize ["modifyvm", :id, "--macaddress2", "080027000002"]
      virtualbox.customize ["modifyvm", :id, "--hostonlyadapter2", "vboxnet0"]

      virtualbox.customize ["modifyvm", :id, "--accelerate3d", "on"]
      virtualbox.customize ["modifyvm", :id, "--vram", "128"]
          
      virtualbox.memory = "2048"
      virtualbox.gui    = true
    end
  
    # remnux.vm.network "private_network",
    #   type: "dhcp",
    #   libvirt__network_name: "default",
    #   libvirt__model_type: "e1000",
    #   libvirt__mac: "52:54:00:07:66:ea",
    #   auto_config: false

    # remnux.vm.network "private_network",
    #   ip: "192.168.55.10",
    #   libvirt__network_name: "hostonly",
    #   libvirt__forward_mode: "none",
    #   libvirt__dhcp_enabled: false,
    #   libvirt__model_type: "e1000",
    #   libvirt__mac: "52:54:00:07:66:eb",
    #   auto_config: false

    
    remnux.vm.provider "libvirt" do |libvirt, override|
      libvirt.mgmt_attach    = false
      
      override.vm.network "forwarded_port",
        guest: 22,
        host: 2223,
        auto_correct: true

      override.vm.network "private_network",
        type: "dhcp",
        libvirt__model_type: "e1000",
        libvirt__network_name: "default",
        mac: "52:54:00:00:00:03"

      override.vm.network "private_network",
        type: "dhcp",
        libvirt__model_type: "e1000",
        libvirt__network_name: "hostonly",
        mac: "52:54:00:00:00:04"

      libvirt.memory = 2048
    end

  end
end