Vagrant.configure("2") do |config|
  # FLARE VM
  config.vm.define "flarevm" do |flarevm|
    flarevm.vm.box = "flarevm-qemu"
    flarevm.vm.hostname = "flarevm"
    flarevm.vm.guest = :windows
    flarevm.ssh.username = "admin"
    flarevm.ssh.password = "password"
    flarevm.ssh.insert_key = false
    flarevm.ssh.shell = "powershell"

    flarevm.vm.synced_folder '.', '/vagrant', disabled: true

    flarevm.vm.provider "vmware_desktop" do |vmware|
      vmware.vmx["ethernet0.present"]        = "TRUE"
      vmware.vmx["ethernet0.connectionType"] = "nat"
      vmware.vmx["ethernet0.virtualDev"]     = "e1000"
      vmware.vmx["ethernet0.connect"]        = "connected"
      vmware.vmx["ethernet0.startConnected"] = "TRUE"
      vmware.vmx["ethernet0.displayName"]    = "nat"
      vmware.vmx["ethernet0.addressType"]    = "static"
      vmware.vmx["ethernet0.address"]        = "00:0c:29:00:00:01"
      vmware.vmx["ethernet0.pciSlotNumber"]  = "33"

      vmware.vmx["ethernet1.present"]        = "TRUE"
      vmware.vmx["ethernet1.connectionType"] = "hostonly"
      vmware.vmx["ethernet1.virtualDev"]     = "e1000"
      vmware.vmx["ethernet1.connect"]        = "connected"
      vmware.vmx["ethernet1.startConnected"] = "TRUE"
      vmware.vmx["ethernet1.displayName"]    = "hostonly"
      vmware.vmx["ethernet1.addressType"]    = "static"
      vmware.vmx["ethernet1.address"]        = "00:0c:29:00:00:02"
      vmware.vmx["ethernet1.pciSlotNumber"]  = "36" # (Windows 11) change to 32 to avoid hostonly NIC issues
      
      vmware.memory = "4096"
      vmware.gui    = true
    end

    flarevm.vm.provider "virtualbox" do |virtualbox|
      virtualbox.customize ["modifyvm", :id, "--nic1", "nat"]
      virtualbox.customize ["modifyvm", :id, "--macaddress1", "080027000001"]
      virtualbox.customize ["modifyvm", :id, "--nic2", "hostonly"]
      virtualbox.customize ["modifyvm", :id, "--macaddress2", "080027000002"]
      virtualbox.customize ["modifyvm", :id, "--hostonlyadapter2", "vboxnet0"]

      virtualbox.customize ["modifyvm", :id, "--accelerate3d", "on"]
      virtualbox.customize ["modifyvm", :id, "--vram", "128"]
          
      virtualbox.memory = "4096"
      virtualbox.gui    = true
    end

    flarevm.vm.network "forwarded_port", guest: 22, host: 2223, auto_correct: true
    
    flarevm.vm.network "private_network",
      libvirt__network_name: "default",
      mac: "52:54:00:07:66:ea"

    flarevm.vm.network "private_network",
      libvirt__network_name: "hostonly",
      # libvirt__dhcp_enabled: false,
      mac: "52:54:00:07:66:eb"

    flarevm.vm.provider "libvirt" do |libvirt|
      libvirt.uri            = "qemu:///system"
      libvirt.driver         = "kvm"
      # libvirt.machine_type   = "q35"
      libvirt.cpu_mode       = "host-passthrough"
      libvirt.memory         = 4096
      libvirt.cpus           = 2
      libvirt.nic_model_type = "e1000"
      libvirt.disk_bus       = "ide"
      libvirt.graphics_type  = "spice"
      libvirt.mgmt_attach = false
      # libvirt.management_network_name    = "default"         # Strategy A
      # # libvirt.management_network_address = "192.168.122.0/24"
      # libvirt.management_network_mode    = "nat"
      # libvirt.management_network_mac     = "52:54:00:00:00:01"

      # libvirt.vm.network "forwarded_port", guest: 22, host: 2222, id: "ssh"
      # libvirt.network "public_network", bridge: "virbr1"

      # libvirt.qemuargs :value => "-netdev"
      # libvirt.qemuargs :value => "user,id=user.0,hostfwd=tcp::2222-:22"
      # libvirt.qemuargs :value => "-device"
      # libvirt.qemuargs :value => "e1000,netdev=user.0,mac=52:54:00:00:00:01"


      # libvirt.qemuargs :value => "-netdev"
      # libvirt.qemuargs :value => "bridge,id=hn1,br=virbr1"
      # libvirt.qemuargs :value => "-device"
      # libvirt.qemuargs :value => "e1000,netdev=hn1,mac=52:54:00:00:00:02"
    end
  
  end
end
